name: Frontend Development Integration Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
     
jobs:
  build:

    runs-on: windows-2019
    env:
      SOLUTION_NAME: SpecIFicator.Frontend-dev.sln
      DEFAULT_PLUGIN_PUBLISH_DIRECTORY: .\src\SpecIFicator.DefaultPlugin\src\bin\Release\net6.0\publish\
      DEFAULT_PLUGIN_CSS_BUNDLE_FILE: .\src\SpecIFicator.DefaultPlugin\src\obj\Release\net6.0\scopedcss\projectbundle\SpecIFicator.DefaultPlugin.bundle.scp.css
      CSS_TARGET_DIRECTORY: .\output\SpecIFicator\wwwroot\_content\SpecIFicator.Framework\css\pluginStyles\
      DEFAULT_PLUGIN_PATH: .\output\SpecIFicator.DefaultPlugin\
      

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Set version number from date using PS
      uses: Amadevus/pwsh-script@v2
      id: date-version
      with:
        script: |
            ([datetime]::now).tostring("yyyy.M.d")

    - name: Set version variable from date and build number
      env: 
        DATE_VERSION: ${{steps.date-version.outputs.result}}
      run: echo ("VERSION=" + $env:DATE_VERSION + "." + $env:GITHUB_RUN_NUMBER) >> $env:GITHUB_ENV

    - name: Echo version number
      run: echo $env:VERSION

    - name: Restore dependencies
      run: dotnet restore ./src/${{env.SOLUTION_NAME}}

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{env.VERSION}} ./src/${{env.SOLUTION_NAME}}
