name: SpecIFictor Development Integration Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019
    env:
      BACKEND_SOLUTION_NAME: SpecIF_Backend-dev.sln 
      FRONTEND_SOLUTION_NAME: SpecIFicator.Frontend-dev.sln

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x


    - name: Set version number from date using PS
      uses: Amadevus/pwsh-script@v2
      id: date-version
      with:
        script: |
            ([datetime]::now).tostring("yyyy.M.d")

    - name: Set version variable from date and build number
      env: 
        DATE_VERSION: ${{steps.date-version.outputs.result}}
      run: echo ("VERSION=" + $env:DATE_VERSION + "." + $env:GITHUB_RUN_NUMBER) >> $env:GITHUB_ENV

    - name: Echo version number
      run: echo $env:VERSION

    - name: Restore backend dependencies
      run: dotnet restore ./src/${{env.BACKEND_SOLUTION_NAME}}

    - name: Restore frontend dependencies
      run: dotnet restore ./src/${{env.FRONTEND_SOLUTION_NAME}}

    - name: Build backend
      run: dotnet build --no-restore -c Release /p:Version=${{env.VERSION}} ./src/${{env.BACKEND_SOLUTION_NAME}}

    - name: Build frontend
      run: dotnet build --no-restore -c Release /p:Version=${{env.VERSION}} ./src/${{env.FRONTEND_SOLUTION_NAME}}